// Coefficients for lib/probability.js's logistic blend — GENERATED by scripts/backtest.js on 2026-09-17T17:36:23.214Z
// against seasons [2023,2024,2025]. Re-run that script to refresh these against more recent
// history; don't hand-edit the backtested values below without re-running it, or this comment will start lying.
// See scripts/backtest.js's header for exactly what this backtest can and can't prove, and README's
// "Probability model" section for the plain-language version.
export const MODEL_COEFFS = {
  // Not backtested (scripts/backtest.js only touches the named factor coefficients below) — hand-set at 12
  // "games" of trust behind the market's own number after checking it against dry-run's thin-vs-deep-sample
  // regression test: at 6, a bare 2-game 100% streak alone moved the estimate over 12 points off the market,
  // almost as aggressively as a real 10+3-game trend — exactly the kind of small-sample overreaction the old
  // point-scoring system was built on. At 12, the same 2-game streak moves it ~7 points while a real deep trend
  // still moves it ~20.
  marketPriorWeight: 12,

  form_hot: 0.283,
  tendency_usage_bump: 0.18, // not backtestable — no historical injury-report feed
  usage_high_snap: 0.293,
  redzone_share: 0.233,
  weak_defense: 0.03,
  matchup_edge: -0.027,
  high_scoring_env: 0.04,
  starter_change: 0.031,
  secondary_injury: 0.15, // not backtestable — no historical injury-report feed
  oline_injury_penalty: -0.2, // not backtestable — no historical injury-report feed
  short_week_penalty: 0.06,
  travel_penalty: -0.095,
  steam_move: 0.1, // not backtestable — no historical odds-movement archive

  // Weather/venue/practice-trend nudges: added when game lines were removed to wire in factors that were
  // already being computed every refresh but never actually scored (see README's "holes" writeup). None of
  // these are backtestable the way form/usage/redzone are — there's no historical archive of past forecasts,
  // dome/outdoor splits, or day-by-day practice reports to replay scripts/backtest.js against — so they're
  // hand-set, deliberately conservative (smaller than the backtested factors above), pending a future season of
  // real archived weather/practice-report data to calibrate against properly.
  weather_personal_boost: 0.15, // not backtestable — no historical weather-forecast archive
  weather_personal_penalty: -0.15, // not backtestable — no historical weather-forecast archive
  weather_run_favor: 0.12, // not backtestable — no historical weather-forecast archive
  weather_pass_penalty: -0.12, // not backtestable — no historical weather-forecast archive
  venue_edge: 0.15, // not backtestable — dome/outdoor split already computed, but not cross-referenced against a
                     // scored bet's own roof anywhere until now
  practice_trend_down: -0.15, // not backtestable — no day-by-day historical practice-report archive
  practice_trend_up: 0.08, // not backtestable — no day-by-day historical practice-report archive

  // Added alongside: opposing front-seven injuries (run-game mirror of secondary_injury above) and game-script
  // (Vegas's own implied spread/total, read as context rather than a bet — see factors/index.js's
  // computeGameScript). Unlike the weather/venue/practice-trend block above, these two ARE now backtestable —
  // scripts/backtest.js measures game_script_* from nflverse's own historical spread_line/total_line columns,
  // the same schedule file already being fetched. front_seven_injury stays hand-set for the same reason
  // secondary_injury does: no historical injury-report archive exists to replay against. Run `npm run backtest`
  // to get a real measured value for game_script_run_favor/game_script_pass_favor instead of these hand-set
  // starting points.
  front_seven_injury: 0.15, // not backtestable — no historical injury-report feed (mirrors secondary_injury)
  game_script_run_favor: 0.1, // backtestable (nflverse spread_line/total_line) — hand-set until you run the backtest
  game_script_pass_favor: 0.08, // backtestable (nflverse spread_line/total_line) — hand-set until you run the backtest

  // Referee tendency revived as a non-bettable context factor (previously tied to the since-removed Totals
  // market) — real historical data (nflverse's own referee/total/total_line schedule columns), and, like
  // game_script_*/venue_edge, genuinely backtestable against that same historical archive; scripts/backtest.js
  // now measures it, these are hand-set starting points until you run `npm run backtest`.
  referee_over_lean: 0.12, // backtestable (nflverse referee/total/total_line) — hand-set until you run the backtest
  referee_under_lean: -0.12, // backtestable (nflverse referee/total/total_line) — hand-set until you run the backtest

  // Next Gen Stats player efficiency (CPOE, rush yards over expected, separation) and pass-protection/pressure —
  // this round's "deep stats" build. Both draw on real, full-history nflverse archives (NGS back to 2016, every
  // sack/qb_hit play-by-play column back as far as pbp is fetched), so both are genuine backtest candidates for
  // a future pass — hand-set for now since neither has actually been run through scripts/backtest.js yet.
  ngs_cpoe_hot: 0.15,
  ngs_cpoe_cold: -0.15,
  ngs_ryoe_hot: 0.12,
  ngs_ryoe_cold: -0.12,
  ngs_separation_hot: 0.1,
  pressure_risk_penalty: -0.12,
  clean_pocket_boost: 0.1,

  generatedAt: "2026-09-17T17:36:23.214Z",
  source: "backtest",
  _backtestSeasons: [2023,2024,2025],
  _backtestSampleSizes: {
  "form_hot": {
    "withN": 13015,
    "withoutN": 23535
  },
  "weak_defense": {
    "withN": 13617,
    "withoutN": 22933
  },
  "matchup_edge": {
    "withN": 13541,
    "withoutN": 23009
  },
  "high_scoring_env": {
    "withN": 7565,
    "withoutN": 28985
  },
  "usage_high_snap": {
    "withN": 11400,
    "withoutN": 25150
  },
  "redzone_share": {
    "withN": 2244,
    "withoutN": 34306
  },
  "starter_change": {
    "withN": 8362,
    "withoutN": 28188
  },
  "short_week_penalty": {
    "withN": 2627,
    "withoutN": 33923
  },
  "travel_penalty": {
    "withN": 4294,
    "withoutN": 32256
  }
}
};
