// Coefficients for lib/probability.js's logistic blend — GENERATED by scripts/backtest.js on 2026-09-19T04:27:18.485Z
// against seasons [2025,2024,2023]. Re-run that script to refresh these against more recent
// history; don't hand-edit the backtested values below without re-running it, or this comment will start lying.
// See scripts/backtest.js's header for exactly what this backtest can and can't prove, and README's
// "Probability model" section for the plain-language version.
export const MODEL_COEFFS = {
  // Not backtested (scripts/backtest.js only touches the named factor coefficients below) — hand-set at 12
  // "games" of trust behind the market's own number after checking it against dry-run's thin-vs-deep-sample
  // regression test: at 6, a bare 2-game 100% streak alone moved the estimate over 12 points off the market,
  // almost as aggressively as a real 10+3-game trend — exactly the kind of small-sample overreaction the old
  // point-scoring system was built on. At 12, the same 2-game streak moves it ~7 points while a real deep trend
  // still moves it ~20.
  marketPriorWeight: 12,

  form_hot: 0.283, // real signal (p=0.000) — kept
  tendency_usage_bump: 0.18, // not backtestable — no historical injury-report feed
  usage_high_snap: 0.293, // real signal (p=0.000) — kept
  redzone_share: 0.233, // real signal (p=0.000) — kept
  weak_defense: 0, // no significant signal (p=0.169) — PRUNED to 0
  matchup_edge: 0, // no significant signal (p=0.215) — PRUNED to 0
  high_scoring_env: 0, // no significant signal (p=0.117) — PRUNED to 0
  starter_change: 0, // no significant signal (p=0.213) — PRUNED to 0
  secondary_injury: 0.15, // not backtestable — no historical injury-report feed
  oline_injury_penalty: -0.2, // not backtestable — no historical injury-report feed
  short_week_penalty: 0, // no significant signal (p=0.134) — PRUNED to 0
  travel_penalty: -0.095, // real signal (p=0.003) — kept
  steam_move: 0.1, // not backtestable — no historical odds-movement archive
  stale_line_value: 0.12, // not backtestable — no historical multi-book odds archive to replay cross-book corroboration against

  // Weather/venue/practice-trend nudges: weather_run_favor, weather_pass_penalty, and venue_edge are now
  // backtested — the first two against Open-Meteo's historical archive (the same source lib/pipeline.js's live
  // backfill uses), venue_edge against the schedule's own roof column, both already being fetched. Personal
  // weather history (weather_personal_boost/penalty) and practice_trend_down/up stay hand-set: there's no
  // per-player historical forecast archive or day-by-day practice-report history to replay them against.
  weather_personal_boost: 0.15, // not backtestable — no historical weather-forecast archive
  weather_personal_penalty: -0.15, // not backtestable — no historical weather-forecast archive
  weather_run_favor: 0.12, // not enough data — kept at prior default
  weather_pass_penalty: -0.12, // not enough data — kept at prior default
  venue_edge: 0.15, // not enough data — kept at prior default
  practice_trend_down: -0.15, // not backtestable — no day-by-day historical practice-report archive
  practice_trend_up: 0.08, // not backtestable — no day-by-day historical practice-report archive

  // Opposing front-seven injuries (run-game mirror of secondary_injury above) and game-script (Vegas's own
  // implied spread/total, read as context rather than a bet — see factors/index.js's computeGameScript).
  // game_script_run_favor/game_script_pass_favor are backtested against nflverse's own historical
  // spread_line/total_line columns; front_seven_injury stays hand-set for the same reason secondary_injury does
  // — no historical injury-report archive exists to replay it against.
  front_seven_injury: 0.15, // not backtestable — no historical injury-report feed (mirrors secondary_injury)
  game_script_run_favor: 0, // no significant signal (p=0.085) — PRUNED to 0
  game_script_pass_favor: -0.091, // real signal (p=0.008) — kept

  // Referee tendency, revived as a non-bettable context factor after this build dropped its Totals market (see
  // lib/factors/referee.js) — backtested walk-forward against nflverse's own historical referee/total/total_line
  // schedule columns, using only each referee's games strictly before the one being tested.
  referee_over_lean: 0, // no significant signal (p=0.332) — PRUNED to 0
  referee_under_lean: 0, // no significant signal (p=0.138) — PRUNED to 0

  // Next Gen Stats player efficiency (CPOE, rush yards over expected, separation) and pass-protection/pressure —
  // real full-history nflverse/play-by-play archives exist for both, making them genuine future backtest
  // candidates, but neither is wired into this script's walk-forward loop yet — hand-set for now.
  ngs_cpoe_hot: 0.15,
  ngs_cpoe_cold: -0.15,
  ngs_ryoe_hot: 0.12,
  ngs_ryoe_cold: -0.12,
  ngs_separation_hot: 0.1,
  pressure_risk_penalty: -0.12,
  clean_pocket_boost: 0.1,

  // Real ESPN Total QBR trend (lib/factors/qbr.js) — nflverse's own espn_data release covers 2006-present, a
  // genuine full-history archive, so this is a real future backtest candidate the same way ngs_*/pressure_*
  // above are — not wired into this script's walk-forward loop yet, hand-set for now.
  qbr_trend_elite: 0.15,
  qbr_trend_poor: -0.15,

  generatedAt: "2026-09-19T04:27:18.485Z",
  source: "backtest",
  _backtestSeasons: [2025,2024,2023],
  _backtestSampleSizes: {
  "form_hot": {
    "withN": 13015,
    "withoutN": 23535
  },
  "weak_defense": {
    "withN": 13617,
    "withoutN": 22933
  },
  "matchup_edge": {
    "withN": 13541,
    "withoutN": 23009
  },
  "high_scoring_env": {
    "withN": 7565,
    "withoutN": 28985
  },
  "usage_high_snap": {
    "withN": 11400,
    "withoutN": 25150
  },
  "redzone_share": {
    "withN": 2244,
    "withoutN": 34306
  },
  "starter_change": {
    "withN": 8362,
    "withoutN": 28188
  },
  "short_week_penalty": {
    "withN": 2627,
    "withoutN": 33923
  },
  "travel_penalty": {
    "withN": 4294,
    "withoutN": 32256
  },
  "weather_run_favor": {
    "withN": 0,
    "withoutN": 2746
  },
  "weather_pass_penalty": {
    "withN": 0,
    "withoutN": 8564
  },
  "venue_edge": {
    "withN": 0,
    "withoutN": 0
  },
  "game_script_run_favor": {
    "withN": 1466,
    "withoutN": 6696
  },
  "game_script_pass_favor": {
    "withN": 4016,
    "withoutN": 21830
  },
  "referee_over_lean": {
    "withN": 482,
    "withoutN": 35568
  },
  "referee_under_lean": {
    "withN": 2801,
    "withoutN": 33249
  }
},
  _backtestVerdicts: {
  "form_hot": "real signal (p=0.000) — kept",
  "weak_defense": "no significant signal (p=0.169) — PRUNED to 0",
  "matchup_edge": "no significant signal (p=0.215) — PRUNED to 0",
  "high_scoring_env": "no significant signal (p=0.117) — PRUNED to 0",
  "usage_high_snap": "real signal (p=0.000) — kept",
  "redzone_share": "real signal (p=0.000) — kept",
  "starter_change": "no significant signal (p=0.213) — PRUNED to 0",
  "short_week_penalty": "no significant signal (p=0.134) — PRUNED to 0",
  "travel_penalty": "real signal (p=0.003) — kept",
  "weather_run_favor": "not enough data — kept at prior default",
  "weather_pass_penalty": "not enough data — kept at prior default",
  "venue_edge": "not enough data — kept at prior default",
  "game_script_run_favor": "no significant signal (p=0.085) — PRUNED to 0",
  "game_script_pass_favor": "real signal (p=0.008) — kept",
  "referee_over_lean": "no significant signal (p=0.332) — PRUNED to 0",
  "referee_under_lean": "no significant signal (p=0.138) — PRUNED to 0"
}
};
