// Coefficients for lib/probability.js's logistic blend — GENERATED by scripts/backtest.js on 2026-09-17T17:36:23.214Z
// against seasons [2023,2024,2025]. Re-run that script to refresh these against more recent
// history; don't hand-edit the backtested values below without re-running it, or this comment will start lying.
// See scripts/backtest.js's header for exactly what this backtest can and can't prove, and README's
// "Probability model" section for the plain-language version.
export const MODEL_COEFFS = {
  // Not backtested (scripts/backtest.js only touches the named factor coefficients below) — hand-set at 12
  // "games" of trust behind the market's own number after checking it against dry-run's thin-vs-deep-sample
  // regression test: at 6, a bare 2-game 100% streak alone moved the estimate over 12 points off the market,
  // almost as aggressively as a real 10+3-game trend — exactly the kind of small-sample overreaction the old
  // point-scoring system was built on. At 12, the same 2-game streak moves it ~7 points while a real deep trend
  // still moves it ~20.
  marketPriorWeight: 12,

  form_hot: 0.283,
  tendency_usage_bump: 0.18, // not backtestable — no historical injury-report feed
  usage_high_snap: 0.293,
  redzone_share: 0.233,
  weak_defense: 0.03,
  matchup_edge: -0.027,
  high_scoring_env: 0.04,
  starter_change: 0.031,
  secondary_injury: 0.15, // not backtestable — no historical injury-report feed
  oline_injury_penalty: -0.2, // not backtestable — no historical injury-report feed
  short_week_penalty: 0.06,
  travel_penalty: -0.095,
  steam_move: 0.1, // not backtestable — no historical odds-movement archive

  generatedAt: "2026-09-17T17:36:23.214Z",
  source: "backtest",
  _backtestSeasons: [2023,2024,2025],
  _backtestSampleSizes: {
  "form_hot": {
    "withN": 13015,
    "withoutN": 23535
  },
  "weak_defense": {
    "withN": 13617,
    "withoutN": 22933
  },
  "matchup_edge": {
    "withN": 13541,
    "withoutN": 23009
  },
  "high_scoring_env": {
    "withN": 7565,
    "withoutN": 28985
  },
  "usage_high_snap": {
    "withN": 11400,
    "withoutN": 25150
  },
  "redzone_share": {
    "withN": 2244,
    "withoutN": 34306
  },
  "starter_change": {
    "withN": 8362,
    "withoutN": 28188
  },
  "short_week_penalty": {
    "withN": 2627,
    "withoutN": 33923
  },
  "travel_penalty": {
    "withN": 4294,
    "withoutN": 32256
  }
}
};
